name: Publish to npm

on:
  workflow_run:
    workflows: ["Check"]
    branches: [main]
    types:
      - completed

concurrency:
  group: publish-main
  cancel-in-progress: false

#permissions:
#  id-token: write
#  contents: read

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'

      - name: Installs Deps & Build
        run: |
          set -e
          npm ci
          npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag latest
        #--provenance